# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('invited_private_ceremony', models.BooleanField(default=False)),
                ('invited_public_ceremony', models.BooleanField(default=False)),
                ('invited_reception', models.BooleanField(default=False)),
                ('invited_dinner', models.BooleanField(default=False)),
                ('invited_party', models.BooleanField(default=False)),
                ('coming_private_ceremony', models.BooleanField(default=False)),
                ('coming_public_ceremony', models.BooleanField(default=False)),
                ('coming_reception', models.BooleanField(default=False)),
                ('coming_dinner', models.BooleanField(default=False)),
                ('coming_party', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuestChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_menus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GuestCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='guestchildren',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.GuestCode'),
        ),
        migrations.AddField(
            model_name='guest',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='main.GuestCode'),
        ),
    ]
