# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restrictions', models.CharField(max_length=500)),
                ('music_request', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.GuestCode')),
            ],
        ),
    ]
