# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guestcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcomments',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='guestcomments',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='guestcomments',
            name='music_request',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
