# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170427_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcode',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
